"""SQLAlchemy 2.0 declarative models for the Prism warehouse.

Role of this module
-------------------
These models are the *typed description* of the schema, not its definition. The
Alembic revisions in ``alembic/versions/`` are authoritative for DDL; this file
mirrors them so that:

* ``alembic revision --autogenerate`` has something to diff against, and any
  accidental drift between code and database shows up as a proposed migration;
* the seeder and tests get real type checking on column names and types;
* the ER diagram and data dictionary in ``docs/`` can be generated from metadata.

The read path does **not** go through the ORM. Repositories execute named SQL
from ``app/sql/queries/`` via SQLAlchemy Core, because these are analytical
queries — window functions, ``FILTER`` clauses, date spines, lateral joins —
that the ORM would only obscure. Using the ORM for aggregate analytics also
tends to produce accidental N+1 patterns, which is why every relationship below
is declared ``lazy="raise"``: touching one outside an explicit eager load raises
instead of silently issuing a query per row.

Materialized views are absent by design. ``analytics.mv_*`` objects are created
in revision 0006 and queried as raw SQL; SQLAlchemy cannot model a materialized
view, and ``alembic/env.py`` excludes the whole ``analytics`` schema from
autogenerate so it never proposes dropping them.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Final

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import CHAR, ENUM, JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# ---------------------------------------------------------------------------
# Naming convention
#
# Applied to any constraint or index created without an explicit name. Every
# object in the migrations *is* explicitly named, so this exists to keep
# autogenerated future objects consistent rather than letting PostgreSQL invent
# names like `users_country_id_fkey1`.
# ---------------------------------------------------------------------------
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}

#: Schema holding the 13 source-of-truth tables.
CORE_SCHEMA: Final[str] = "core"

#: Schema holding derived materialized views. Named here for documentation and
#: for the repositories that reference it in raw SQL.
ANALYTICS_SCHEMA: Final[str] = "analytics"


class Base(DeclarativeBase):
    """Declarative base for every Prism table.

    ``MetaData.schema`` defaults all tables to ``core``, which keeps the schema
    qualifier out of thirteen ``__table_args__`` blocks. Alembic's bookkeeping
    table stays in ``public`` via ``version_table_schema=None`` in ``env.py``.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION, schema=CORE_SCHEMA)

    type_annotation_map = {  # noqa: RUF012 - SQLAlchemy reads this as a plain dict
        Decimal: Numeric,
        datetime: DateTime(timezone=True),
    }


# ---------------------------------------------------------------------------
# Enum types
#
# `create_type=False` on every one: revision 0001 owns their lifecycle. Without
# it, SQLAlchemy would emit CREATE TYPE during `metadata.create_all()` in tests
# and fail on a duplicate object.
# ---------------------------------------------------------------------------
content_type_enum: Final[ENUM] = ENUM(
    "movie",
    "series",
    "documentary",
    "stand_up",
    name="content_type",
    schema=CORE_SCHEMA,
    create_type=False,
)

event_name_enum: Final[ENUM] = ENUM(
    "OPEN_APP",
    "HOME",
    "BROWSE_GENRE",
    "SEARCH",
    "VIEW_CONTENT",
    "WATCH_TRAILER",
    "START_VIDEO",
    "VIDEO_PROGRESS",
    "PAUSE_VIDEO",
    "ABANDON_VIDEO",
    "COMPLETE_VIDEO",
    "ADD_TO_WATCHLIST",
    "RATE",
    "SUBSCRIBE_CLICK",
    "EXIT",
    name="event_name",
    schema=CORE_SCHEMA,
    create_type=False,
)

sub_status_enum: Final[ENUM] = ENUM(
    "trialing",
    "active",
    "paused",
    "cancelled",
    "expired",
    name="sub_status",
    schema=CORE_SCHEMA,
    create_type=False,
)

billing_period_enum: Final[ENUM] = ENUM(
    "monthly",
    "quarterly",
    "annual",
    name="billing_period",
    schema=CORE_SCHEMA,
    create_type=False,
)

exp_status_enum: Final[ENUM] = ENUM(
    "running",
    "completed",
    "stopped",
    name="exp_status",
    schema=CORE_SCHEMA,
    create_type=False,
)


# ===========================================================================
# Dimensions
#
# Rows for all six are inserted by revision 0002, not the seeder: the API
# validates incoming filter values against these tables, so a migrated-but-
# unseeded database must still serve a working /users endpoint.
# ===========================================================================


class Country(Base):
    """A market Vireo operates in."""

    __tablename__ = "countries"
    __table_args__ = (
        UniqueConstraint("iso_code", name="uq_countries_iso_code"),
        UniqueConstraint("name", name="uq_countries_name"),
        CheckConstraint("tier BETWEEN 1 AND 3", name="ck_countries_tier_range"),
        CheckConstraint("iso_code = upper(iso_code)", name="ck_countries_iso_upper"),
        {"comment": "Markets Vireo operates in. tier is a monetisation band."},
    )

    country_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    iso_code: Mapped[str] = mapped_column(CHAR(2))
    name: Mapped[str] = mapped_column(String(64))
    region: Mapped[str] = mapped_column(String(32))
    tier: Mapped[int] = mapped_column(
        SmallInteger,
        comment="1 = high ARPU / high CAC, 2 = mid, 3 = high volume / low ARPU.",
    )


class Device(Base):
    """A playback surface.

    ``form_factor`` rather than ``platform`` is the primary analytical grouping:
    a phone session behaves like a phone session on either OS, while a TV
    session is several times longer.
    """

    __tablename__ = "devices"
    __table_args__ = (
        UniqueConstraint("name", name="uq_devices_name"),
        CheckConstraint(
            "form_factor IN ('phone', 'tablet', 'desktop', 'tv', 'console')",
            name="ck_devices_form_factor",
        ),
        {"comment": "Playback surfaces. form_factor is the primary analytical grouping."},
    )

    device_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    name: Mapped[str] = mapped_column(String(48))
    platform: Mapped[str] = mapped_column(String(16))
    form_factor: Mapped[str] = mapped_column(String(16))


class MarketingChannel(Base):
    """An acquisition source with its blended cost."""

    __tablename__ = "marketing_channels"
    __table_args__ = (
        UniqueConstraint("name", name="uq_channels_name"),
        CheckConstraint("cac_usd >= 0", name="ck_channels_cac_non_negative"),
        CheckConstraint(
            "is_paid OR cac_usd = 0 OR name = 'Email'",
            name="ck_channels_unpaid_has_no_cac",
        ),
        {"comment": "Acquisition sources with blended CAC. Drives LTV:CAC and payback."},
    )

    channel_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    name: Mapped[str] = mapped_column(String(48))
    channel_group: Mapped[str] = mapped_column(String(24))
    is_paid: Mapped[bool] = mapped_column(Boolean)
    cac_usd: Mapped[Decimal] = mapped_column(
        Numeric(8, 2),
        comment="Blended customer acquisition cost in USD. Zero for organic.",
    )


class Persona(Base):
    """A behavioural archetype and its base rates.

    These three coefficients are simulation *inputs*: the seeder perturbs them
    per user to drive session frequency, completion and churn. The analytics
    layer then recovers the same relationships independently, which is what makes
    the retention-by-persona chart a genuine finding rather than decoration.
    """

    __tablename__ = "personas"
    __table_args__ = (
        UniqueConstraint("name", name="uq_personas_name"),
        CheckConstraint("base_sessions_per_week > 0", name="ck_personas_sessions_positive"),
        CheckConstraint(
            "base_completion_rate BETWEEN 0 AND 1", name="ck_personas_completion_is_rate"
        ),
        CheckConstraint(
            "base_churn_propensity BETWEEN 0 AND 1", name="ck_personas_churn_is_rate"
        ),
        {"comment": "Behavioural archetypes. Coefficients are simulation inputs."},
    )

    persona_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    name: Mapped[str] = mapped_column(String(32))
    description: Mapped[str] = mapped_column(Text)
    base_sessions_per_week: Mapped[Decimal] = mapped_column(Numeric(4, 2))
    base_completion_rate: Mapped[Decimal] = mapped_column(Numeric(4, 3))
    base_churn_propensity: Mapped[Decimal] = mapped_column(
        Numeric(4, 3),
        comment="Monthly churn hazard before per-user perturbation and tenure decay.",
    )


class Genre(Base):
    """A catalogue genre."""

    __tablename__ = "genres"
    __table_args__ = (
        UniqueConstraint("name", name="uq_genres_name"),
        {"comment": "Catalogue genres. A table, not an enum: the business adds genres."},
    )

    genre_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    name: Mapped[str] = mapped_column(String(32))


class SubscriptionPlan(Base):
    """A commercial plan.

    ``monthly_price_usd`` is list price. Realised MRR applies the billing-period
    discount, which is why annual subscribers show lower MRR but higher LTV.
    """

    __tablename__ = "subscription_plans"
    __table_args__ = (
        UniqueConstraint("name", name="uq_plans_name"),
        CheckConstraint("monthly_price_usd >= 0", name="ck_plans_price_non_negative"),
        CheckConstraint("max_streams BETWEEN 1 AND 8", name="ck_plans_streams_range"),
        CheckConstraint(
            "tier IN ('free', 'entry', 'standard', 'premium')", name="ck_plans_tier"
        ),
        CheckConstraint(
            "(tier = 'free') = (monthly_price_usd = 0)", name="ck_plans_free_tier_is_free"
        ),
        {"comment": "Commercial plans. List price; MRR applies the billing-period discount."},
    )

    plan_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    name: Mapped[str] = mapped_column(String(32))
    tier: Mapped[str] = mapped_column(String(16))
    monthly_price_usd: Mapped[Decimal] = mapped_column(Numeric(6, 2))
    max_streams: Mapped[int] = mapped_column(SmallInteger)
    has_ads: Mapped[bool] = mapped_column(Boolean)


# ===========================================================================
# Entities — populated exclusively by `python -m seeder`
# ===========================================================================


class User(Base):
    """A registered Vireo account.

    ``is_premium``, ``last_seen_at`` and ``churned_at`` are current-state columns
    maintained by the seeder as the simulation advances. They duplicate
    information recoverable from ``subscriptions`` and ``events``, and exist
    because "how many premium users right now" is asked on every page load and
    should not require a correlated subquery over subscription history.
    """

    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint(
            "gender IN ('male', 'female', 'non_binary', 'undisclosed')", name="ck_users_gender"
        ),
        CheckConstraint("age BETWEEN 13 AND 90", name="ck_users_age_range"),
        CheckConstraint("signup_date <= CURRENT_DATE", name="ck_users_no_future_signup"),
        CheckConstraint(
            "churned_at IS NULL OR churned_at >= signup_date", name="ck_users_churn_after_signup"
        ),
        CheckConstraint(
            r"app_version ~ '^[0-9]+\.[0-9]+\.[0-9]+$'", name="ck_users_app_version_semver"
        ),
        Index("ix_users_signup_date", "signup_date"),
        Index("ix_users_country", "country_id"),
        Index("ix_users_channel", "channel_id"),
        Index("ix_users_persona", "persona_id"),
        Index("ix_users_device", "device_id"),
        Index("ix_users_premium", "user_id", postgresql_where=text("is_premium")),
        Index(
            "ix_users_churned_at", "churned_at", postgresql_where=text("churned_at IS NOT NULL")
        ),
        Index(
            "ix_users_last_seen",
            "last_seen_at",
            postgresql_where=text("last_seen_at IS NOT NULL"),
        ),
        Index("ix_users_signup_channel", "signup_date", "channel_id"),
        {"comment": "Vireo subscriber base. One row per registered account."},
    )

    user_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    signup_date: Mapped[date] = mapped_column(Date)

    country_id: Mapped[int] = mapped_column(
        SmallInteger, ForeignKey("countries.country_id", name="fk_users_country", onupdate="CASCADE")
    )
    device_id: Mapped[int] = mapped_column(
        SmallInteger,
        ForeignKey("devices.device_id", name="fk_users_device", onupdate="CASCADE"),
        comment="Device used at signup. Sessions carry their own device_id.",
    )
    channel_id: Mapped[int] = mapped_column(
        SmallInteger,
        ForeignKey(
            "marketing_channels.channel_id", name="fk_users_channel", onupdate="CASCADE"
        ),
    )
    persona_id: Mapped[int] = mapped_column(
        SmallInteger, ForeignKey("personas.persona_id", name="fk_users_persona", onupdate="CASCADE")
    )

    is_premium: Mapped[bool] = mapped_column(
        Boolean,
        server_default=text("false"),
        comment="Current paid state. Denormalised from subscriptions for read speed.",
    )
    gender: Mapped[str] = mapped_column(String(16))
    age: Mapped[int] = mapped_column(SmallInteger)
    app_version: Mapped[str] = mapped_column(String(12))
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    churned_at: Mapped[date | None] = mapped_column(
        Date, comment="Date the user was classified as churned. NULL means active."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # lazy="raise" throughout: these exist for ORM ergonomics in tests and
    # scripts. The read path uses named SQL, and an accidental lazy load inside a
    # loop should fail loudly rather than become an N+1.
    country: Mapped[Country] = relationship(lazy="raise")
    device: Mapped[Device] = relationship(lazy="raise")
    channel: Mapped[MarketingChannel] = relationship(lazy="raise")
    persona: Mapped[Persona] = relationship(lazy="raise")


class Content(Base):
    """A catalogue title.

    ``popularity_score`` is an editorial signal that drives selection weight
    during generation. Because it is an input rather than a measurement, the
    "popularity vs completion rate" scatter on the Content page compares two
    genuinely independent axes.
    """

    __tablename__ = "content"
    __table_args__ = (
        UniqueConstraint("title", "release_year", name="uq_content_title_year"),
        CheckConstraint("runtime_minutes BETWEEN 1 AND 400", name="ck_content_runtime_range"),
        CheckConstraint("release_year BETWEEN 1950 AND 2030", name="ck_content_year_range"),
        CheckConstraint("popularity_score BETWEEN 0 AND 100", name="ck_content_popularity_range"),
        CheckConstraint(
            "age_rating IN ('U', 'U/A 7+', 'U/A 13+', 'U/A 16+', 'A')",
            name="ck_content_age_rating",
        ),
        CheckConstraint(
            "(content_type = 'series') = (season_count IS NOT NULL)",
            name="ck_content_series_has_seasons",
        ),
        CheckConstraint(
            "(content_type = 'series') = (episode_count IS NOT NULL)",
            name="ck_content_series_has_episodes",
        ),
        CheckConstraint(
            "season_count IS NULL OR season_count BETWEEN 1 AND 20",
            name="ck_content_season_range",
        ),
        CheckConstraint(
            "episode_count IS NULL OR episode_count BETWEEN 1 AND 400",
            name="ck_content_episode_range",
        ),
        Index("ix_content_genre", "genre_id"),
        Index("ix_content_type", "content_type"),
        Index("ix_content_popularity", text("popularity_score DESC")),
        Index("ix_content_genre_type", "genre_id", "content_type"),
        Index("ix_content_added_on", "added_on"),
        Index(
            "ix_content_title_trgm",
            text("title gin_trgm_ops"),
            postgresql_using="gin",
        ),
        {"comment": "Vireo catalogue. Fictional titles; see docs/seeder-design.md."},
    )

    content_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    title: Mapped[str] = mapped_column(String(200))
    genre_id: Mapped[int] = mapped_column(
        SmallInteger, ForeignKey("genres.genre_id", name="fk_content_genre", onupdate="CASCADE")
    )
    content_type: Mapped[str] = mapped_column(content_type_enum)
    runtime_minutes: Mapped[int] = mapped_column(
        SmallInteger, comment="Per-episode runtime for series, total for films."
    )
    release_year: Mapped[int] = mapped_column(SmallInteger)
    language: Mapped[str] = mapped_column(String(32))
    age_rating: Mapped[str] = mapped_column(String(8))
    popularity_score: Mapped[Decimal] = mapped_column(
        Numeric(5, 2), comment="Editorial 0-100 signal. Drives selection weight."
    )
    season_count: Mapped[int | None] = mapped_column(SmallInteger)
    episode_count: Mapped[int | None] = mapped_column(SmallInteger)
    is_original: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    added_on: Mapped[date] = mapped_column(Date)

    genre: Mapped[Genre] = relationship(lazy="raise")


class Session(Base):
    """One app-open to app-close.

    ``duration_seconds``, ``event_count`` and ``watch_seconds`` are denormalised
    from ``events``. That is a considered trade: the session page computes
    percentiles over hundreds of thousands of sessions, and deriving them from
    millions of event rows per request would turn a 40ms query into seconds.
    ``tests/test_seeder.py`` asserts they agree with a recomputation.
    """

    __tablename__ = "sessions"
    __table_args__ = (
        CheckConstraint("session_end >= session_start", name="ck_sessions_end_after_start"),
        CheckConstraint("session_start <= now()", name="ck_sessions_no_future_start"),
        CheckConstraint("duration_seconds >= 0", name="ck_sessions_duration_non_negative"),
        CheckConstraint("duration_seconds <= 43200", name="ck_sessions_duration_sane"),
        CheckConstraint("event_count >= 2", name="ck_sessions_min_events"),
        CheckConstraint("watch_seconds >= 0", name="ck_sessions_watch_non_negative"),
        CheckConstraint(
            "watch_seconds <= duration_seconds", name="ck_sessions_watch_within_duration"
        ),
        CheckConstraint(
            "entry_screen IN ('splash', 'home', 'search', 'browse', 'detail', "
            "'player', 'watchlist', 'profile', 'settings', 'paywall')",
            name="ck_sessions_entry_screen",
        ),
        CheckConstraint(
            "exit_screen IN ('splash', 'home', 'search', 'browse', 'detail', "
            "'player', 'watchlist', 'profile', 'settings', 'paywall')",
            name="ck_sessions_exit_screen",
        ),
        Index("ix_sessions_user_start", "user_id", "session_start"),
        Index("ix_sessions_start", "session_start"),
        Index("ix_sessions_device", "device_id"),
        Index("ix_sessions_duration", "duration_seconds"),
        Index(
            "ix_sessions_first",
            "user_id",
            "session_start",
            postgresql_where=text("is_first_session"),
        ),
        Index(
            "ix_sessions_with_watch",
            "session_start",
            "watch_seconds",
            postgresql_where=text("watch_seconds > 0"),
        ),
        {"comment": "One row per app-open to app-close. Parent of events."},
    )

    session_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.user_id", name="fk_sessions_user", ondelete="CASCADE")
    )
    device_id: Mapped[int] = mapped_column(
        SmallInteger,
        ForeignKey("devices.device_id", name="fk_sessions_device", onupdate="CASCADE"),
        comment="Device for THIS session, which may differ from the signup device.",
    )
    session_start: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    session_end: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    duration_seconds: Mapped[int] = mapped_column(
        Integer, comment="Denormalised from session_end - session_start."
    )
    event_count: Mapped[int] = mapped_column(
        SmallInteger, comment="Denormalised count of events rows for this session."
    )
    watch_seconds: Mapped[int] = mapped_column(
        Integer,
        server_default=text("0"),
        comment="Denormalised sum of playback seconds within this session.",
    )
    is_first_session: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    entry_screen: Mapped[str] = mapped_column(String(32))
    exit_screen: Mapped[str] = mapped_column(String(32))

    user: Mapped[User] = relationship(lazy="raise")
    device: Mapped[Device] = relationship(lazy="raise")


class Event(Base):
    """One clickstream event — the fact table.

    Range-partitioned monthly on ``event_time``. The primary key is
    ``(event_id, event_time)`` because PostgreSQL requires the partition key to
    participate in every unique constraint on a partitioned table; ``event_id``
    is still globally unique in practice, drawing from one shared sequence.

    ``watch_seconds`` is *incremental* — seconds since that content's previous
    playback event — so ``SUM(watch_seconds)`` is correct at any grain.
    ``progress_pct`` is *cumulative* and monotonic within
    ``(session_id, content_id)``. The analytics layer depends on this contract.

    Cross-row journey invariants (``START_VIDEO`` before ``COMPLETE_VIDEO``,
    ``RATE`` only after a completion, monotonic progress) cannot be expressed as
    ``CHECK`` constraints. They are enforced by the generator and asserted in
    ``tests/test_seeder.py``.
    """

    __tablename__ = "events"
    __table_args__ = (
        CheckConstraint("event_time <= now()", name="ck_events_no_future_time"),
        CheckConstraint("step_index >= 0", name="ck_events_step_index"),
        CheckConstraint(
            "screen IN ('splash', 'home', 'search', 'browse', 'detail', "
            "'player', 'watchlist', 'profile', 'settings', 'paywall')",
            name="ck_events_screen",
        ),
        CheckConstraint(
            "watch_seconds IS NULL OR event_name IN "
            "('VIDEO_PROGRESS', 'PAUSE_VIDEO', 'ABANDON_VIDEO', 'COMPLETE_VIDEO')",
            name="ck_events_watch_only_on_playback",
        ),
        CheckConstraint(
            "progress_pct IS NULL OR event_name IN "
            "('VIDEO_PROGRESS', 'PAUSE_VIDEO', 'ABANDON_VIDEO', 'COMPLETE_VIDEO')",
            name="ck_events_progress_only_on_playback",
        ),
        CheckConstraint(
            "watch_seconds IS NULL OR watch_seconds >= 0", name="ck_events_watch_non_negative"
        ),
        CheckConstraint(
            "progress_pct IS NULL OR progress_pct BETWEEN 0 AND 100",
            name="ck_events_progress_range",
        ),
        CheckConstraint(
            "event_name <> 'COMPLETE_VIDEO' OR "
            "(progress_pct IS NOT NULL AND progress_pct >= 90)",
            name="ck_events_complete_is_complete",
        ),
        CheckConstraint(
            "CASE "
            "WHEN event_name IN ('VIEW_CONTENT', 'WATCH_TRAILER', 'START_VIDEO', "
            "'VIDEO_PROGRESS', 'PAUSE_VIDEO', 'ABANDON_VIDEO', 'COMPLETE_VIDEO', "
            "'ADD_TO_WATCHLIST', 'RATE') THEN content_id IS NOT NULL "
            "WHEN event_name IN ('OPEN_APP', 'HOME', 'SEARCH', 'EXIT') "
            "THEN content_id IS NULL "
            "ELSE true END",
            name="ck_events_content_id_presence",
        ),
        CheckConstraint(
            "jsonb_typeof(properties) = 'object'", name="ck_events_properties_is_object"
        ),
        Index("ix_events_user_time", "user_id", "event_time"),
        Index("ix_events_session_step", "session_id", "step_index"),
        Index("ix_events_name_time", "event_name", "event_time"),
        Index(
            "ix_events_content_time",
            "content_id",
            "event_time",
            postgresql_where=text("content_id IS NOT NULL"),
        ),
        Index(
            "ix_events_playback_covering",
            "content_id",
            "event_name",
            "event_time",
            postgresql_include=["watch_seconds", "progress_pct"],
            postgresql_where=text(
                "event_name IN ('START_VIDEO', 'COMPLETE_VIDEO', 'ABANDON_VIDEO')"
            ),
        ),
        Index(
            "ix_events_time_brin",
            "event_time",
            postgresql_using="brin",
            postgresql_with={"pages_per_range": 32},
        ),
        Index(
            "ix_events_search_query",
            text("(properties ->> 'search_query')"),
            postgresql_where=text("event_name = 'SEARCH'"),
        ),
        {
            "postgresql_partition_by": "RANGE (event_time)",
            "comment": (
                "Clickstream fact table, range-partitioned monthly on event_time. "
                "Cross-row journey invariants are enforced by the generator."
            ),
        },
    )

    event_id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    event_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), primary_key=True)

    session_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("sessions.session_id", name="fk_events_session", ondelete="CASCADE"),
    )
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.user_id", name="fk_events_user", ondelete="CASCADE")
    )
    content_id: Mapped[int | None] = mapped_column(
        BigInteger,
        ForeignKey("content.content_id", name="fk_events_content", ondelete="RESTRICT"),
    )

    event_name: Mapped[str] = mapped_column(event_name_enum)
    screen: Mapped[str] = mapped_column(String(32))
    step_index: Mapped[int] = mapped_column(
        SmallInteger,
        comment="Zero-based position within the session; breaks timestamp ties.",
    )
    watch_seconds: Mapped[int | None] = mapped_column(
        Integer, comment="Incremental seconds since this content's previous playback event."
    )
    progress_pct: Mapped[Decimal | None] = mapped_column(
        Numeric(5, 2), comment="Cumulative, monotonic within (session_id, content_id)."
    )
    properties: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        server_default=text("'{}'::jsonb"),
        comment="Event-specific payload: search_query, rating, genre_browsed, error_code.",
    )


class Subscription(Base):
    """One subscription term.

    Full history, not current state: a user who subscribed, cancelled and
    returned has three rows. That is what makes MRR movement — new, expansion,
    contraction, churn, reactivation — computable rather than approximated.
    """

    __tablename__ = "subscriptions"
    __table_args__ = (
        CheckConstraint(
            "ended_on IS NULL OR ended_on >= started_on", name="ck_subs_end_after_start"
        ),
        CheckConstraint("started_on <= CURRENT_DATE", name="ck_subs_no_future_start"),
        CheckConstraint("mrr_usd >= 0", name="ck_subs_mrr_non_negative"),
        CheckConstraint(
            "(ended_on IS NULL) = (status IN ('trialing', 'active', 'paused'))",
            name="ck_subs_status_matches_open_state",
        ),
        CheckConstraint(
            "cancel_reason IS NULL OR status IN ('cancelled', 'expired')",
            name="ck_subs_reason_requires_cancel",
        ),
        Index("ix_subs_user_started", "user_id", "started_on"),
        Index("ix_subs_status", "status"),
        Index("ix_subs_plan", "plan_id"),
        Index("ix_subs_started_on", "started_on"),
        Index(
            "ix_subs_active", "user_id", "mrr_usd", postgresql_where=text("ended_on IS NULL")
        ),
        Index("ix_subs_ended_on", "ended_on", postgresql_where=text("ended_on IS NOT NULL")),
        {"comment": "Full subscription history. Multiple rows per user."},
    )

    subscription_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.user_id", name="fk_subscriptions_user", ondelete="CASCADE")
    )
    plan_id: Mapped[int] = mapped_column(
        SmallInteger,
        ForeignKey(
            "subscription_plans.plan_id", name="fk_subscriptions_plan", onupdate="CASCADE"
        ),
    )
    started_on: Mapped[date] = mapped_column(Date)
    ended_on: Mapped[date | None] = mapped_column(
        Date, comment="NULL means the subscription is still open."
    )
    status: Mapped[str] = mapped_column(sub_status_enum)
    billing_period: Mapped[str] = mapped_column(billing_period_enum)
    mrr_usd: Mapped[Decimal] = mapped_column(
        Numeric(8, 2), comment="Monthly recurring revenue after the billing-period discount."
    )
    cancel_reason: Mapped[str | None] = mapped_column(String(48))
    is_trial_conversion: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))

    user: Mapped[User] = relationship(lazy="raise")
    plan: Mapped[SubscriptionPlan] = relationship(lazy="raise")


class Experiment(Base):
    """An A/B test definition. Results are computed in SQL, never stored."""

    __tablename__ = "experiments"
    __table_args__ = (
        UniqueConstraint("key", name="uq_experiments_key"),
        CheckConstraint("key ~ '^[a-z0-9-]+$'", name="ck_experiments_key_slug"),
        CheckConstraint(
            "traffic_allocation > 0 AND traffic_allocation <= 1",
            name="ck_experiments_allocation_range",
        ),
        CheckConstraint(
            "ended_on IS NULL OR ended_on >= started_on", name="ck_experiments_end_after_start"
        ),
        CheckConstraint(
            "(status = 'running') = (ended_on IS NULL)",
            name="ck_experiments_running_has_no_end",
        ),
        CheckConstraint(
            "jsonb_typeof(variants) = 'array' AND jsonb_array_length(variants) >= 2",
            name="ck_experiments_min_two_variants",
        ),
        CheckConstraint(
            "primary_metric IN ('subscription_conversion', 'completion_rate', "
            "'session_duration', 'sessions_per_user', 'trailer_to_start', 'day7_retention')",
            name="ck_experiments_primary_metric",
        ),
        {"comment": "A/B test registry. Results are computed in SQL, not stored."},
    )

    experiment_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    key: Mapped[str] = mapped_column(
        String(64), comment="Stable slug used in URLs, e.g. 'autoplay-preview-v2'."
    )
    name: Mapped[str] = mapped_column(String(120))
    hypothesis: Mapped[str] = mapped_column(Text)
    primary_metric: Mapped[str] = mapped_column(String(48))
    variants: Mapped[list[str]] = mapped_column(
        JSONB, comment='Ordered variant names, control first: ["control", "variant_a"].'
    )
    traffic_allocation: Mapped[Decimal] = mapped_column(
        Numeric(3, 2), comment="Fraction of eligible users enrolled, 0-1."
    )
    started_on: Mapped[date] = mapped_column(Date)
    ended_on: Mapped[date | None] = mapped_column(Date)
    status: Mapped[str] = mapped_column(exp_status_enum)


class ExperimentAssignment(Base):
    """Which user saw which variant.

    The bridge table a nine-table sketch of this schema would omit: user-to-
    experiment is many-to-many. The composite primary key guarantees a user
    cannot be enrolled twice in one experiment, which would otherwise
    double-count them in every significance test.
    """

    __tablename__ = "experiment_assignments"
    __table_args__ = (
        CheckConstraint("assigned_at <= now()", name="ck_assignments_no_future_assignment"),
        Index("ix_assignments_exp_variant", "experiment_id", "variant"),
        Index("ix_assignments_user", "user_id"),
        {"comment": "Composite PK prevents double enrolment in the same experiment."},
    )

    experiment_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey(
            "experiments.experiment_id", name="fk_assignments_experiment", ondelete="CASCADE"
        ),
        primary_key=True,
    )
    user_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("users.user_id", name="fk_assignments_user", ondelete="CASCADE"),
        primary_key=True,
    )
    variant: Mapped[str] = mapped_column(String(32))
    assigned_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    experiment: Mapped[Experiment] = relationship(lazy="raise")


# ---------------------------------------------------------------------------
# Public surface
# ---------------------------------------------------------------------------

#: Table names in a valid insert order, respecting foreign keys. The seeder's
#: ``--truncate`` path reverses this to delete children before parents.
INSERT_ORDER: Final[tuple[str, ...]] = (
    "countries",
    "devices",
    "marketing_channels",
    "personas",
    "genres",
    "subscription_plans",
    "users",
    "content",
    "sessions",
    "events",
    "subscriptions",
    "experiments",
    "experiment_assignments",
)

#: Tables the seeder owns. The six dimensions are excluded: revision 0002 owns
#: their rows, and truncating them would break API filter validation.
SEEDED_TABLES: Final[tuple[str, ...]] = (
    "users",
    "content",
    "sessions",
    "events",
    "subscriptions",
    "experiments",
    "experiment_assignments",
)

__all__ = [
    "ANALYTICS_SCHEMA",
    "CORE_SCHEMA",
    "INSERT_ORDER",
    "SEEDED_TABLES",
    "Base",
    "Content",
    "Country",
    "Device",
    "Event",
    "Experiment",
    "ExperimentAssignment",
    "Genre",
    "MarketingChannel",
    "Persona",
    "Session",
    "Subscription",
    "SubscriptionPlan",
    "User",
]
